import React from "react";
import Head from "next/head";
import { NextPage } from "next";
import { useRouter } from "next/router";
import { trpc } from "../../../../../utils/trpc";


const FindBuilds: NextPage = () => {
  const { opponentRace, raceName } = useRouter().query as {
    opponentRace: string,
    raceName: string
  };

  const builds = trpc.builds.getBuildsByMatchUp.useQuery(
    {matchUp: `${raceName.toLowerCase().charAt(0)}v${opponentRace.toLowerCase().charAt(0)}`}
  );

  return (
    <>
      <Head>
        <title>race</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col items-center justify-center text-black gap-4">
        <h1>{raceName} X {opponentRace} </h1>

        <table>
          <thead>
          <tr>
            <th>Id</th>
            <th>Match Up</th>
            <th>Build</th>
          </tr>
          </thead>
          <tbody>
          {builds.data?.map((build) => (
            <tr key={build.id}>
              <td>{build.id}</td>
              <td>{build.matchUp}</td>
              <td>{build.build}</td>
            </tr>
          ))}
          </tbody>
        </table>

      </main>
    </>
  )
}

export default FindBuilds;