import React from "react";
import Head from "next/head";
import { RaceCard } from "../../../../Components/RaceCard";
import { NextPage } from "next";
import { useRouter } from "next/router";


const FindBuilds: NextPage = () => {
  const raceName = useRouter().query.raceName;

  return (
    <>
      <Head>
        <title>race</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col items-center justify-center text-black gap-4">
        <div className="text-center flex flex-col gap-4">
          <p>{raceName}</p>
          <p>X</p>
          <p>Select your opponent</p>
        </div>
        <ul className="grid grid-cols-3 gap-4">
          <li>
            <RaceCard href={`/races/zerg/match-ups/zerg`} raceImageSrc={"./fraunhofer.jpg"} raceName="Zerg" isOpponent={true} ></RaceCard>
          </li>
          <li>
            <RaceCard href={`/races/proto/match-ups/proto`} raceImageSrc={"./fraunhofer.jpg"} raceName="Proto" isOpponent={true}></RaceCard>
          </li>
          <li>
            <RaceCard href={`/races/terran/match-ups/terran`} raceImageSrc={"./fraunhofer.jpg"} raceName="Terran" isOpponent={true}></RaceCard>
          </li>
        </ul>

      </main>
    </>
  )
}

export default FindBuilds;