import { type NextPage } from "next";
import Head from "next/head";
import React, { useState } from "react";
import { trpc } from "../utils/trpc";
import Link from "next/link";

const BuildsPage: NextPage = () => {

  const builds = trpc.builds.getBuilds.useQuery();

  return (
    <>
      <Head>
        <title>Builds</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={"gap-4 flex min-h-screen flex-col items-center justify-center bg-indigo-500 text-white"}>
        <h1>Builds</h1>

        <Link href="/">Menu</Link>

        <table>
          <thead>
            <tr>
              <th>Id</th>
              <th>Match Up</th>
              <th>Build</th>
            </tr>
          </thead>
          <tbody>
          {builds.data?.map((build) => (
            <tr key={build.id}>
              <td>{build.id}</td>
              <td>{build.matchUp}</td>
              <td>{build.build}</td>
            </tr>
          ))}
          </tbody>
        </table>
      </main>

    </>
  );
};

export default BuildsPage;
