import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  // const hello = trpc.example.hello.useQuery({ text: "from tRPC" });
  const [buildOrder, setBuildOrder] = useState("");

  return (
    <>
      <Head>
        <title>Testing List</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/*<main className="mx-auto my-12 max-w-3xl">*/}
      {/*  <div className="flex justify-between">*/}
      {/*    <h2 className="text-2x1 font-semi-bold">Shopping List</h2>*/}
      {/*    <button type="button" className="bg-blue-500 text-sm text-white p-2 rounded-md transition hover:bg-blue-600">Add item</button>*/}
      {/*  </div>*/}
      {/*</main>*/}
      <main className={"gap-4 flex min-h-screen flex-col items-center justify-center bg-indigo-500 text-white"}>
        <h1>Submit a Build Order</h1>
        <label htmlFor={"match-up-select"}> Match up </label>
        <select id="match-up-select">
          <option value="ZvT">ZvT</option>
          <option value="zvp">ZvP</option>
          <option value="zvz">ZvZ</option>
        </select>

        <textarea
          className="text-black p-2"
          value={buildOrder}
          onChange={(e) => setBuildOrder(e.target.value)}
        />

        <button className="bg-blue-500 text-sm text-white p-2 rounded-md transition hover:bg-blue-600">Submit</button>
      </main>

    </>
  );
};

export default Home;
