import { type NextPage } from "next";
import Head from "next/head";
import React, { useState } from "react";
import { trpc } from "../utils/trpc";
import Link from "next/link";

const Home: NextPage = () => {
  const createBuildMutation = trpc.builds.createBuild.useMutation();

  const [matchUp, setMatchUp] = useState("");
  const [build, setBuild] = useState("");
  async function handleSubmitBuildOrder(e: React.FormEvent) {
    e.preventDefault();
    await createBuildMutation.mutateAsync({
      matchUp,
      build,
    })
  }

  return (
    <>
      <Head>
        <title>Testing List</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/*<main className="mx-auto my-12 max-w-3xl">*/}
      {/*  <div className="flex justify-between">*/}
      {/*    <h2 className="text-2x1 font-semi-bold">Shopping List</h2>*/}
      {/*    <button type="button" className="bg-blue-500 text-sm text-white p-2 rounded-md transition hover:bg-blue-600">Add item</button>*/}
      {/*  </div>*/}
      {/*</main>*/}

      <main className={"gap-4 flex min-h-screen flex-col items-center justify-center bg-indigo-500 text-white"}>
        <h1>Welcome to a build manager</h1>

        <Link href="/submit-build">Submit Build</Link>

      </main>

    </>
  );
};

export default Home;
