import React from "react";
import Link from "next/link";
import Head from "next/head";
import { RaceCard } from "../Components/RaceCard";
import { NextPage } from "next";


const Races: NextPage = () => {
  return (
    <>
      <Head>
        <title>Find Builds</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col items-center justify-center text-black gap-4">
        <h1>Select your race</h1>

        <ul className="grid grid-cols-3 gap-4">
          <li>
            <RaceCard href={`/races/zerg/match-ups`} raceImageSrc={"./fraunhofer.jpg"} raceName="Zerg" isOpponent={false}></RaceCard>
          </li>
          <li>
            <RaceCard href={`/races/proto/match-ups`} raceImageSrc={"./fraunhofer.jpg"} raceName="Proto" isOpponent={false}></RaceCard>
          </li>
          <li>
            <RaceCard href={`/races/terran/match-ups`} raceImageSrc={"./fraunhofer.jpg"} raceName="Terran" isOpponent={false}></RaceCard>
          </li>
        </ul>

      </main>
    </>
  )
}

export default Races;