import { type NextPage } from "next";
import Head from "next/head";
import React, { useState } from "react";
import { trpc } from "../utils/trpc";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const createBuildMutation = trpc.builds.createBuild.useMutation();

  const [matchUp, setMatchUp] = useState("");
  const [build, setBuild] = useState("");

  const router = useRouter();

  async function handleSubmitBuildOrder(e: React.FormEvent) {
    e.preventDefault();
    await createBuildMutation.mutateAsync({
      matchUp,
      build,
    });
    await router.push('/');
  }

  return (
    <>
      <Head>
        <title>Submit a Build</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={"gap-4 flex min-h-screen flex-col items-center justify-center bg-indigo-500 text-white"}>
        <h1>Submit a Build Order</h1>
        <form
          className="flex flex-col gap-2"
          onSubmit={handleSubmitBuildOrder}
        >
          <label htmlFor={"match-up-select"}> Match up </label>
          <select
            className="text-black"
            value={matchUp}
            onChange={e => setMatchUp(e.target.value)}
            id="match-up-select" required
          >
            <option value="ZvT">ZvT</option>
            <option value="zvp">ZvP</option>
            <option value="zvz">ZvZ</option>
          </select>

          <textarea
            required
            className="text-black p-2"
            value={build}
            onChange={(e) => setBuild(e.target.value)}
          />

          <button className="bg-blue-500 text-sm text-white p-2 rounded-md transition hover:bg-blue-600">Submit</button>
        </form>
      </main>

    </>
  );
};

export default Home;
